apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: mysecret
  namespace: secret
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: mysecret
    uid: 78f42060-3035-4d79-9219-a5fb2472b591
type: Opaque
